# 21 -> 7[1] -> 21[1] (200 blocks)
A:
  E_E_hidden_weight_scale: 5.997826E+00
  E_E_learning_rate: 9.553728E-01
  E_E_output_weight_scale: 4.849485E-01
  E_I_hidden_weight_scale: 9.877346E-01
  E_I_learning_rate: 0.000000E+00
  E_I_output_weight_scale: 1.850915E-01
  I_E_hidden_weight_scale: 1.000000E+00
  I_E_learning_rate: 0.000000E+00
  I_E_output_weight_scale: 1.000000E+00
  I_I_hidden_weight_scale: 0.000000E+00
  I_I_learning_rate: 0.000000E+00
  I_I_output_weight_scale: 0.000000E+00
# 21 -> 7[7] -> 21[7] (200 blocks)
B:
  E_E_hidden_weight_scale: 9.927103E+00
  E_E_learning_rate: 2.339308E-01
  E_E_output_weight_scale: 5.066363E+00
  E_I_hidden_weight_scale: 2.128817E+00
  E_I_learning_rate: 2.023946E-01
  E_I_output_weight_scale: 9.054215E+00
  I_E_hidden_weight_scale: 1.597438E+00
  I_E_learning_rate: 5.947580E-02
  I_E_output_weight_scale: 7.679770E+00
  I_I_hidden_weight_scale: 5.040185E+00
  I_I_learning_rate: 2.982688E-01
  I_I_output_weight_scale: 3.343300E-01
# 21 -> 7[7] -> 21[7] (200 blocks)
anti_Hebb:
  E_E_hidden_weight_scale: 3.255803E+00
  E_E_learning_rate: 2.756839E-01
  E_E_output_weight_scale: 8.436103E-01
  E_I_hidden_weight_scale: 2.352644E+00
  E_I_learning_rate: 1.415294E-02
  E_I_output_weight_scale: 1.589356E+00
  I_E_hidden_weight_scale: 1.925080E+00
  I_E_learning_rate: 3.213503E-01
  I_E_output_weight_scale: 7.526584E+00
  I_I_hidden_weight_scale: 1.877143E+00
  I_I_learning_rate: 4.600147E-02
  I_I_output_weight_scale: 1.979838E+00
