# 7 -> 21[1] (200 blocks)
A:
  E_E_learning_rate: 4.999473E-01
  E_E_weight_scale: 2.454925E+00
  E_I_learning_rate: 0.
  E_I_weight_scale: 5.038043E+00
  I_E_learning_rate: 0.
  I_E_weight_scale: 1.
  I_I_learning_rate: 0.
  I_I_weight_scale: 0.
