bounds:
  output_FF_max_weight:
    - 1.5
    - 5.
  output_layer_pos_mod_th:
    - 0.05
    - 0.5
  output_layer_neg_mod_th:
    - -0.5
    - -0.05
  output_layer_pos_mod_learning_rate:
    - 0.01
    - 0.25
  FF_max_init_weight_factor:
    - 0.1
    - 2.
  E_I_soma_max_init_weight:
    - -2.
    - -0.1
  I_soma_E_max_init_weight:
    - 0.1
    - 1.
  neg_mod_pre_discount:
    - 0.1
    - 0.5
default_params:
  I_soma_E_max_init_weight: 1.
  neg_mod_pre_discount: 0.25
feature_names:
- MSE_loss
get_features_stages:
- source: nested_optimize_simple_BTSP_network_no_hidden
  compute_features: compute_features
get_objectives:
  nested_optimize_simple_BTSP_network_no_hidden: get_objectives
objective_names:
- MSE_loss
optimization_title: simple_BTSP_network_no_hidden
param_gen: PopulationAnnealing
x0:
  output_FF_max_weight: 4.1352592
  output_layer_pos_mod_th: 0.10097198
  output_layer_neg_mod_th: -0.1216729
  output_layer_pos_mod_learning_rate: 0.02084186
  FF_max_init_weight_factor: 0.65164461
  E_I_soma_max_init_weight: -0.2
  I_soma_E_max_init_weight: 1.
  neg_mod_pre_discount: 0.25