bounds:
  E_E_learning_rate:
    - 0.0001
    - 0.5
  E_I_learning_rate:
    - 0.0001
    - 0.5
  I_E_learning_rate:
    - 0.0001
    - 0.5
  I_I_learning_rate:
    - 0.0001
    - 0.5
  E_E_weight_scale:
    - 0.5
    - 10.
  E_I_weight_scale:
    - 0.5
    - 10.
  I_E_weight_scale:
    - 0.5
    - 10.
  I_I_weight_scale:
    - 0.
    - 10.
default_params:
  I_I_weight_scale: 0.
kwargs:
  anti_Hebb_I: True
  output_inh_dim: 1
  num_blocks: 200
feature_names:
- MSE_loss
get_features_stages:
- source: nested_optimize_Hebb_lateral_inh_network_no_hidden
  compute_features: compute_features
get_objectives:
  nested_optimize_Hebb_lateral_inh_network_no_hidden: get_objectives
objective_names:
- MSE_loss
optimization_title: Hebb_lateral_inh_network_no_hidden_A
param_gen: PopulationAnnealing
x0:
  E_E_learning_rate: 4.392767E-01
  E_E_weight_scale: 2.820508E+00
  E_I_learning_rate: 3.851672E-01
  E_I_weight_scale: 4.473693E+00
  I_E_learning_rate: 4.089656E-02
  I_E_weight_scale: 9.937887E+00
  I_I_learning_rate: 3.259708E-02
  I_I_weight_scale: 0.